(function(root){
'use strict';
class CursorEngine{
 constructor(layer){this.layer=layer;this.dot=layer.querySelector('.cursor-dot');this.ring=layer.querySelector('.cursor-ring');this.canvas=layer.querySelector('canvas');this.ctx=this.canvas.getContext('2d');this.cfg=null;this.active=false;this.lowEnd=((navigator.hardwareConcurrency||8)<=4)||((navigator.deviceMemory||8)<=4);this.effectiveStyle='default';this.x=0;this.y=0;this.rx=0;this.ry=0;this.points=[];this.raf=0;this.lastDraw=0;this.pointerFine=matchMedia('(pointer:fine)').matches;this.homeParent=layer.parentNode;this.homeNext=layer.nextSibling;this.move=this.move.bind(this);this.resize=this.resize.bind(this);this.syncTopLayer=this.syncTopLayer.bind(this);addEventListener('pointermove',this.move,{passive:true});addEventListener('resize',this.resize,{passive:true});document.addEventListener('visibilitychange',()=>this.refresh());this.dialogObserver=new MutationObserver(this.syncTopLayer);document.querySelectorAll('dialog').forEach(d=>this.dialogObserver.observe(d,{attributes:true,attributeFilter:['open']}));this.syncTopLayer();this.resize();}
 configure(prefs){this.cfg=prefs;let style=prefs.cursorStyle||'default';if(this.lowEnd&&prefs.adaptivePerformance!==false&&['trail','sparkle','comet','blob'].includes(style))style='ring';this.effectiveStyle=style;this.layer.dataset.style=style;this.layer.style.setProperty('--cursor-size',`${prefs.cursorSize||18}px`);this.layer.style.setProperty('--cursor-color',prefs.cursorColor||'#8da2ff');this.layer.style.setProperty('--cursor-secondary',prefs.cursorSecondary||'#fff');this.layer.style.setProperty('--cursor-glow',`${Math.round((prefs.cursorGlow||0)*.24)}px`);this.layer.style.setProperty('--cursor-rgb-speed',`${prefs.cursorRGBSpeed||8}s`);this.refresh();}
 enabled(){const p=this.cfg;if(!p||!this.pointerFine||p.performance||p.reducedMotion||this.effectiveStyle==='default')return false;return true;}
 syncTopLayer(){const dialogs=[...document.querySelectorAll('dialog[open]')];const target=dialogs.at(-1)||null;if(target){if(this.layer.parentNode!==target)target.appendChild(this.layer);}else if(this.layer.parentNode!==this.homeParent){if(this.homeNext&&this.homeNext.parentNode===this.homeParent)this.homeParent.insertBefore(this.layer,this.homeNext);else this.homeParent.appendChild(this.layer);}this.resize();if(this.cfg)this.refresh();}
 resize(){const d=Math.min(devicePixelRatio||1,1.2),w=innerWidth,h=innerHeight;this.canvas.width=Math.max(1,Math.floor(w*d));this.canvas.height=Math.max(1,Math.floor(h*d));this.canvas.style.width=w+'px';this.canvas.style.height=h+'px';this.ctx.setTransform(d,0,0,d,0,0);this.w=w;this.h=h;}
 move(e){this.x=e.clientX;this.y=e.clientY;if(!this.active)return;const p=this.cfg,style=this.effectiveStyle;if(style==='trail'||style==='sparkle'||style==='comet'){const last=this.points[this.points.length-1];if(!last||Math.hypot(last.x-this.x,last.y-this.y)>4){this.points.push({x:this.x,y:this.y,a:1,r:style==='sparkle'?1.5+Math.random()*2:2});const max=Math.max(3,Math.min(24,p.cursorTrail||8));while(this.points.length>max)this.points.shift();}}}
 refresh(){const on=this.enabled()&&!document.hidden;this.active=on;this.layer.hidden=!on;document.documentElement.dataset.customCursor=String(on);if(on&&!this.raf)this.raf=requestAnimationFrame(t=>this.tick(t));if(!on&&this.raf){cancelAnimationFrame(this.raf);this.raf=0;this.points=[];this.ctx.clearRect(0,0,this.w,this.h);}}
 tick(t){this.raf=0;if(!this.active)return;const p=this.cfg,s=Math.max(.05,Math.min(.5,p.cursorSmoothing||.2));this.rx+=(this.x-this.rx)*s;this.ry+=(this.y-this.ry)*s;this.dot.style.transform=`translate3d(${this.x}px,${this.y}px,0)`;this.ring.style.transform=`translate3d(${this.rx}px,${this.ry}px,0)`;
  const style=this.effectiveStyle;if((style==='trail'||style==='sparkle'||style==='comet')&&t-this.lastDraw>24){this.lastDraw=t;const c=this.ctx;c.clearRect(0,0,this.w,this.h);const fade=Math.max(.04,(100-(p.cursorTrailFade||70))/100+.04);for(let i=0;i<this.points.length;i++){const q=this.points[i];q.a-=fade*.12;const progress=(i+1)/this.points.length;c.globalAlpha=Math.max(0,q.a)*progress*.7;c.fillStyle=p.cursorColor||'#8da2ff';if(style==='comet'){c.beginPath();c.arc(q.x,q.y,Math.max(1,progress*4),0,Math.PI*2);c.fill();}else if(style==='sparkle'){c.save();c.translate(q.x,q.y);c.rotate(t/500+i);c.fillRect(-q.r/2,-q.r*2,q.r,q.r*4);c.fillRect(-q.r*2,-q.r/2,q.r*4,q.r);c.restore();}else{c.beginPath();c.arc(q.x,q.y,Math.max(1,progress*3),0,Math.PI*2);c.fill();}}c.globalAlpha=1;this.points=this.points.filter(q=>q.a>0);}
  this.raf=requestAnimationFrame(x=>this.tick(x));}
 destroy(){removeEventListener('pointermove',this.move);removeEventListener('resize',this.resize);if(this.dialogObserver)this.dialogObserver.disconnect();if(this.raf)cancelAnimationFrame(this.raf);}
}
root.BlobbyCursor={CursorEngine};
})(window);
