(function(root){
'use strict';
class EffectsEngine{
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:true,desynchronized:true});this.items={};this.frame=0;this.last=0;this.lastPaint=0;this.cfg=null;this.w=0;this.h=0;this.lowEnd=((navigator.hardwareConcurrency||8)<=4)||((navigator.deviceMemory||8)<=4);this.resize=this.resize.bind(this);addEventListener('resize',this.resize,{passive:true});document.addEventListener('visibilitychange',()=>this.refresh());}
 configure(prefs,theme){this.cfg={prefs,theme};const r=document.documentElement,e=prefs.effects||{},allow=prefs.effectsMaster&&!prefs.performance&&!prefs.reducedMotion,low=this.lowEnd&&prefs.adaptivePerformance!==false;
  const expensive=new Set(['aurora','fog','waves','rgbGlow','clouds','liquid']);for(const k of ['aurora','fog','waves','rgbGlow','clouds','digitalGrid','neonHorizon','liquid','lightRays'])r.dataset[k]=String(!!e[k]&&allow&&!(low&&expensive.has(k)));
  r.dataset.rainGlass=String(!!prefs.rainGlass&&!!e.rain&&allow);r.dataset.lowPower=String(this.lowEnd&&prefs.adaptivePerformance!==false);this.rebuild();this.refresh();}
 active(){if(!this.cfg)return false;const p=this.cfg.prefs;if(document.hidden||p.performance||p.reducedMotion||!p.effectsMaster)return false;const e=p.effects||{};return ['snow','rain','stars','particles','fireflies','orbs','matrix','bubbles','shooting','dust','constellation','spaceDust'].some(k=>e[k]);}
 effectiveDensity(){const p=this.cfg.prefs;let d=p.effectDensity||40;if(this.lowEnd&&p.adaptivePerformance!==false)d=Math.min(d,45);return d;}
 count(base){return Math.max(3,Math.round(base*(this.effectiveDensity()/50)));}
 resize(){this.resizeCanvasOnly();this.rebuild();}
 resizeCanvasOnly(){const p=this.cfg&&this.cfg.prefs||{},low=this.lowEnd&&p.adaptivePerformance!==false,d=p.performance?1:(low?1:Math.min(devicePixelRatio||1,1.25)),w=innerWidth,h=innerHeight;if(this.w===w&&this.h===h&&this.dpr===d)return;this.dpr=d;this.canvas.width=Math.max(1,Math.floor(w*d));this.canvas.height=Math.max(1,Math.floor(h*d));this.canvas.style.width=w+'px';this.canvas.style.height=h+'px';this.ctx.setTransform(d,0,0,d,0,0);this.w=w;this.h=h;}
 rebuild(){if(!this.cfg)return;this.resizeCanvasOnly();const p=this.cfg.prefs,e=p.effects||{},w=this.w||innerWidth,h=this.h||innerHeight,size=p.effectSize||1;this.items={};
  if(e.snow)this.items.snow=Array.from({length:this.count(34)},()=>({x:Math.random()*w,y:Math.random()*h,r:(.8+Math.random()*2.1)*size,v:13+Math.random()*26,drift:-6+Math.random()*12}));
  if(e.rain)this.items.rain=Array.from({length:this.count(58)},()=>({x:Math.random()*w,y:Math.random()*h,l:(8+Math.random()*16)*size,v:360+Math.random()*380}));
  if(e.stars)this.items.stars=Array.from({length:this.count(52)},()=>({x:Math.random()*w,y:Math.random()*h,r:(.45+Math.random()*1.15)*size,a:.25+Math.random()*.6,t:Math.random()*6}));
  if(e.particles)this.items.particles=Array.from({length:this.count(22)},()=>({x:Math.random()*w,y:Math.random()*h,r:(.8+Math.random()*1.7)*size,vx:-7+Math.random()*14,vy:-7+Math.random()*14}));
  if(e.fireflies)this.items.fireflies=Array.from({length:this.count(13)},()=>({x:Math.random()*w,y:Math.random()*h,r:(1.2+Math.random()*1.8)*size,vx:-8+Math.random()*16,vy:-6+Math.random()*12,t:Math.random()*8}));
  if(e.orbs)this.items.orbs=Array.from({length:this.count(6)},()=>({x:Math.random()*w,y:Math.random()*h,r:(18+Math.random()*42)*size,vx:-3+Math.random()*6,vy:-2+Math.random()*4}));
  if(e.matrix)this.items.matrix=Array.from({length:Math.max(7,Math.round(w/(this.lowEnd?46:32)))},(_,i)=>({x:i*(this.lowEnd?46:32)+Math.random()*12,y:Math.random()*h,v:60+Math.random()*100,char:String.fromCharCode(0x30A0+Math.floor(Math.random()*75))}));
  if(e.bubbles)this.items.bubbles=Array.from({length:this.count(14)},()=>({x:Math.random()*w,y:Math.random()*h,r:(3+Math.random()*8)*size,v:10+Math.random()*24,drift:-6+Math.random()*12}));
  if(e.dust||e.spaceDust)this.items.dust=Array.from({length:this.count(e.spaceDust?46:28)},()=>({x:Math.random()*w,y:Math.random()*h,r:(.45+Math.random()*1.2)*size,vx:-2+Math.random()*4,vy:-1.5+Math.random()*3,a:.1+Math.random()*.35}));
  if(e.shooting)this.items.shooting=[{x:-120,y:h*.2,v:0,next:performance.now()+1800+Math.random()*4000}];
  if(e.constellation)this.items.constellation=Array.from({length:this.count(18)},()=>({x:Math.random()*w,y:Math.random()*h,vx:-3+Math.random()*6,vy:-3+Math.random()*6}));
 }
 refresh(){if(this.active()){this.canvas.hidden=false;if(!this.frame){this.last=0;this.lastPaint=0;this.frame=requestAnimationFrame(t=>this.tick(t));}}else{if(this.frame)cancelAnimationFrame(this.frame);this.frame=0;this.canvas.hidden=true;if(this.w)this.ctx.clearRect(0,0,this.w,this.h);}}
 tick(t){this.frame=0;if(!this.active())return;const p=this.cfg.prefs,low=this.lowEnd&&p.adaptivePerformance!==false,target=low?1000/30:1000/60;if(this.lastPaint&&t-this.lastPaint<target-1){this.frame=requestAnimationFrame(x=>this.tick(x));return;}const dt=this.last?Math.min((t-this.last)/1000,.05):0;this.last=t;this.lastPaint=t;const c=this.ctx,w=this.w,h=this.h,spd=p.effectSpeed||1,alpha=p.effectOpacity||.5,theme=this.cfg.theme||{};c.clearRect(0,0,w,h);
  if(this.items.orbs){for(const o of this.items.orbs){o.x+=o.vx*spd*dt;o.y+=o.vy*spd*dt;if(o.x<-o.r)o.x=w+o.r;if(o.x>w+o.r)o.x=-o.r;if(o.y<-o.r)o.y=h+o.r;if(o.y>h+o.r)o.y=-o.r;c.globalAlpha=alpha*.12;c.fillStyle=theme.accent||'#8da2ff';c.beginPath();c.arc(o.x,o.y,o.r,0,Math.PI*2);c.fill();}}
  if(this.items.stars){c.fillStyle='#fff';for(const s of this.items.stars){s.t+=dt*spd;c.globalAlpha=alpha*s.a*(.68+.32*Math.sin(s.t));c.beginPath();c.arc(s.x,s.y,s.r,0,Math.PI*2);c.fill();}}
  if(this.items.snow){c.fillStyle='#fff';c.globalAlpha=alpha;for(const s of this.items.snow){s.y+=s.v*spd*dt;s.x+=s.drift*spd*dt;if(s.y>h+5){s.y=-5;s.x=Math.random()*w}if(s.x<-5)s.x=w+5;if(s.x>w+5)s.x=-5;c.beginPath();c.arc(s.x,s.y,s.r,0,Math.PI*2);c.fill();}}
  if(this.items.rain){c.strokeStyle=theme.accent2||'#74b7ff';c.lineWidth=1;c.globalAlpha=alpha*.72;c.beginPath();for(const r of this.items.rain){r.y+=r.v*spd*dt;r.x-=r.v*.07*spd*dt;if(r.y>h+30||r.x<-30){r.y=-30-Math.random()*h*.2;r.x=Math.random()*(w+100)}c.moveTo(r.x,r.y);c.lineTo(r.x-r.l*.22,r.y+r.l);}c.stroke();if(p.rainLightning&&!low&&Math.random()<.0012*spd)document.documentElement.animate([{filter:'brightness(1)'},{filter:'brightness(1.35)'},{filter:'brightness(1)'}],{duration:150});}
  if(this.items.particles){c.fillStyle=theme.accent||'#8da2ff';c.globalAlpha=alpha*.45;for(const q of this.items.particles){q.x+=q.vx*spd*dt;q.y+=q.vy*spd*dt;if(q.x<0||q.x>w)q.vx*=-1;if(q.y<0||q.y>h)q.vy*=-1;c.beginPath();c.arc(q.x,q.y,q.r,0,Math.PI*2);c.fill();}}
  if(this.items.fireflies){for(const f of this.items.fireflies){f.t+=dt*spd;f.x+=f.vx*spd*dt;f.y+=f.vy*spd*dt;if(f.x<0||f.x>w)f.vx*=-1;if(f.y<0||f.y>h)f.vy*=-1;const pulse=.35+.65*(.5+.5*Math.sin(f.t*2));c.fillStyle='#d6ff73';c.globalAlpha=alpha*pulse*.75;c.beginPath();c.arc(f.x,f.y,f.r*2.2,0,Math.PI*2);c.fill();c.globalAlpha=alpha*pulse;c.beginPath();c.arc(f.x,f.y,f.r,0,Math.PI*2);c.fill();}}
  if(this.items.matrix){c.font='13px ui-monospace,monospace';c.fillStyle='#63ff7c';for(const m of this.items.matrix){m.y+=m.v*spd*dt;if(m.y>h+20)m.y=-20;c.globalAlpha=alpha*.55;c.fillText(m.char,m.x,m.y);if(Math.random()<.025)m.char=String.fromCharCode(0x30A0+Math.floor(Math.random()*75));}}
  if(this.items.bubbles){c.strokeStyle=theme.accent2||'#7cdcff';c.lineWidth=1;c.globalAlpha=alpha*.55;for(const b of this.items.bubbles){b.y-=b.v*spd*dt;b.x+=b.drift*spd*dt;if(b.y<-15){b.y=h+15;b.x=Math.random()*w}c.beginPath();c.arc(b.x,b.y,b.r,0,Math.PI*2);c.stroke();}}
  if(this.items.dust){c.fillStyle='#fff';for(const d of this.items.dust){d.x+=d.vx*spd*dt;d.y+=d.vy*spd*dt;if(d.x<0)d.x=w;if(d.x>w)d.x=0;if(d.y<0)d.y=h;if(d.y>h)d.y=0;c.globalAlpha=alpha*d.a;c.beginPath();c.arc(d.x,d.y,d.r,0,Math.PI*2);c.fill();}}
  if(this.items.constellation){const pts=this.items.constellation;c.strokeStyle=theme.accent2||'#8da2ff';c.lineWidth=.7;c.fillStyle=theme.accent||'#8da2ff';for(const q of pts){q.x+=q.vx*spd*dt;q.y+=q.vy*spd*dt;if(q.x<0||q.x>w)q.vx*=-1;if(q.y<0||q.y>h)q.vy*=-1;c.globalAlpha=alpha*.65;c.beginPath();c.arc(q.x,q.y,1.2,0,Math.PI*2);c.fill();}for(let i=0;i<pts.length;i++){for(let j=i+1;j<Math.min(pts.length,i+5);j++){const a=pts[i],b=pts[j],dist=Math.hypot(a.x-b.x,a.y-b.y);if(dist<150){c.globalAlpha=alpha*.18*(1-dist/150);c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();}}}}
  if(this.items.shooting){const s=this.items.shooting[0];if(t>s.next){s.v+=1000*dt;s.x+=s.v*dt;s.y+=s.v*.25*dt;c.strokeStyle='#fff';c.lineWidth=1.25;c.globalAlpha=alpha;c.beginPath();c.moveTo(s.x,s.y);c.lineTo(s.x-80,s.y-20);c.stroke();if(s.x>w+140){s.x=-120;s.y=30+Math.random()*h*.45;s.v=0;s.next=t+2500+Math.random()*6500;}}}
  c.globalAlpha=1;this.frame=requestAnimationFrame(x=>this.tick(x));}
 destroy(){if(this.frame)cancelAnimationFrame(this.frame);removeEventListener('resize',this.resize);}
}
root.BlobbyEffects={EffectsEngine};
})(window);
