(()=>{
const CLIENT_ID="cd6cf2b9618c4d6d91f6ca71b49b4874", REDIRECT_URI="https://sevenrevelations.github.io/erelease/spotify-callback.html";
const SCOPES="streaming user-read-email user-read-private user-read-playback-state user-modify-playback-state";
const K={v:"blobby_sp_v",s:"blobby_sp_s",t:"blobby_sp_t",r:"blobby_sp_r",e:"blobby_sp_e"};
const out=(s)=>{let e=document.getElementById("status");if(e)e.textContent=s;};
const enc=b=>btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");
const rand=n=>{let a=new Uint8Array(n);crypto.getRandomValues(a);return enc(a).slice(0,n)};
async function login(){let v=rand(64),s=rand(32);localStorage.setItem(K.v,v);localStorage.setItem(K.s,s);let d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));let q=new URLSearchParams({client_id:CLIENT_ID,response_type:"code",redirect_uri:REDIRECT_URI,scope:SCOPES,state:s,code_challenge_method:"S256",code_challenge:enc(d)});location.href="https://accounts.spotify.com/authorize?"+q}
async function exchange(code){let body=new URLSearchParams({client_id:CLIENT_ID,grant_type:"authorization_code",code,redirect_uri:REDIRECT_URI,code_verifier:localStorage.getItem(K.v)});let r=await fetch("https://accounts.spotify.com/api/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body}),x=await r.json();if(!r.ok)throw Error(x.error_description||x.error);localStorage.setItem(K.t,x.access_token);localStorage.setItem(K.r,x.refresh_token||"");localStorage.setItem(K.e,Date.now()+x.expires_in*1000);location.replace("spotify-test.html")}
async function refresh(){let r0=localStorage.getItem(K.r);if(!r0)return null;let body=new URLSearchParams({client_id:CLIENT_ID,grant_type:"refresh_token",refresh_token:r0});let r=await fetch("https://accounts.spotify.com/api/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body}),x=await r.json();if(!r.ok)return null;localStorage.setItem(K.t,x.access_token);if(x.refresh_token)localStorage.setItem(K.r,x.refresh_token);localStorage.setItem(K.e,Date.now()+x.expires_in*1000);return x.access_token}
async function token(){return Number(localStorage.getItem(K.e)||0)-60000>Date.now()?localStorage.getItem(K.t):await refresh()}
async function start(){let t=await token();if(!t)return out("Spotify authorization required.");if(!window.Spotify)return out("FAIL: Spotify SDK did not load.");out("Authorized. Initializing player…");let p=new Spotify.Player({name:"Blobby Compatibility Test",getOAuthToken:async cb=>cb(await token()),volume:.5});p.addListener("ready",x=>out("PASS: Web Playback SDK initialized.\nDevice ID: "+x.device_id));p.addListener("initialization_error",x=>out("FAIL: initialization_error\n"+x.message));p.addListener("authentication_error",x=>out("Authentication error: "+x.message));p.addListener("account_error",x=>out("Account error: "+x.message+"\nSpotify Premium is required."));p.addListener("playback_error",x=>out("Playback error: "+x.message));if(!await p.connect())out("FAIL: player.connect() returned false.");window.blobbySpotifyTestPlayer=p}
let q=new URLSearchParams(location.search);
if(location.pathname.endsWith("spotify-callback.html")){let code=q.get("code"),state=q.get("state");if(q.get("error"))document.body.textContent="Spotify authorization failed: "+q.get("error");else if(!code||state!==localStorage.getItem(K.s))document.body.textContent="Spotify callback validation failed.";else exchange(code).catch(e=>document.body.textContent="Token exchange failed: "+e.message);return}
document.getElementById("connect")?.addEventListener("click",login);document.getElementById("clear")?.addEventListener("click",()=>{Object.values(K).forEach(k=>localStorage.removeItem(k));out("Test data cleared.")});
window.onSpotifyWebPlaybackSDKReady=()=>start().catch(e=>out("Test error: "+e.message));if(window.Spotify)start().catch(e=>out("Test error: "+e.message));
})();