(function(root){
'use strict';
const C=root.BlobbyCore,COLS=C.GRID_COLS,ROWS=C.GRID_ROWS;
function pos(el){return {col:+el.dataset.gridCol||1,row:+el.dataset.gridRow||1,w:+el.dataset.gridW||1,h:+el.dataset.gridH||1};}
function setPos(el,p,commit=true){el.style.gridColumn=`${p.col} / span ${p.w}`;el.style.gridRow=`${p.row} / span ${p.h}`;if(commit){el.dataset.gridCol=p.col;el.dataset.gridRow=p.row;el.dataset.gridW=p.w;el.dataset.gridH=p.h;}}
function overlaps(a,b){return a.col<b.col+b.w&&a.col+a.w>b.col&&a.row<b.row+b.h&&a.row+a.h>b.row;}
function occupied(container,skip){return [...container.querySelectorAll('[data-layout-item]')].filter(el=>el!==skip&&!el.hidden).map(el=>({el,...pos(el)}));}
function canPlace(container,item,p){if(p.col<1||p.row<1||p.w<1||p.h<1||p.col+p.w-1>COLS||p.row+p.h-1>ROWS)return false;return !occupied(container,item).some(o=>overlaps(p,o));}
function apply(prefs,container=document.getElementById('appShell')){if(!container)return;const hidden=new Set(prefs.layoutHidden||[]);container.dataset.layoutPreset=prefs.layoutPreset||'minimal';container.querySelectorAll('[data-layout-item]').forEach(el=>{const id=el.dataset.layoutItem;let hide=hidden.has(id);if(id==='clock'&&!prefs.showClock)hide=true;if(id==='shortcuts'&&!prefs.showShortcuts)hide=true;if(id==='recent'&&!prefs.showRecent)hide=true;if(id==='preview'&&!prefs.showPreview)hide=true;if(prefs.focusMode&&['clock','shortcuts','recent','preview'].includes(id))hide=true;if(prefs.focusMode&&id==='hero'&&!prefs.focusKeepLogo)hide=true;el.hidden=hide;});
 const mobile=innerWidth<=700&&prefs.mobileAutoLayout!==false&&container.dataset.layoutEditing!=='true';const grid=C.sanitizeGrid(mobile?C.layoutPresets.mobile.grid:(prefs.layoutGrid||C.defaultLayoutGrid));container.dataset.mobileLayout=String(mobile);const placed=[];for(const id of C.layoutItemIds){const el=container.querySelector(`[data-layout-item="${id}"]`);if(!el||el.hidden)continue;let q={...grid[id]};const free=x=>x.col>=1&&x.row>=1&&x.col+x.w-1<=COLS&&x.row+x.h-1<=ROWS&&!placed.some(o=>overlaps(x,o));if(!free(q)){outer:for(let r=1;r<=ROWS-q.h+1;r++)for(let c=1;c<=COLS-q.w+1;c++){const test={...q,col:c,row:r};if(free(test)){q=test;break outer;}}}grid[id]=q;setPos(el,q,true);placed.push(q);}if(!mobile)prefs.layoutGrid=grid;}
function usePreset(prefs,id){const preset=C.layoutPresets[id]||C.layoutPresets.minimal;prefs.layoutPreset=id;prefs.layoutGrid=C.clone(preset.grid);prefs.layoutHidden=C.clone(preset.hidden);return prefs;}
function ensureGuide(container){const guide=container.querySelector('#layoutGridGuide');if(!guide)return null;if(!guide.childElementCount){const frag=document.createDocumentFragment();for(let r=1;r<=ROWS;r++)for(let c=1;c<=COLS;c++){const cell=document.createElement('i');cell.dataset.col=c;cell.dataset.row=r;frag.append(cell);}guide.append(frag);}return guide;}
function paintGuide(container,p,valid){const g=ensureGuide(container);if(!g)return;g.querySelectorAll('i.active,i.blocked').forEach(x=>x.className='');if(!p)return;for(let r=p.row;r<p.row+p.h;r++)for(let c=p.col;c<p.col+p.w;c++){const cell=g.querySelector(`i[data-col="${c}"][data-row="${r}"]`);if(cell)cell.className=valid?'active':'blocked';}}
function clearGuide(container){const g=ensureGuide(container);if(g)g.querySelectorAll('i.active,i.blocked').forEach(x=>x.className='');}
function enableEditor(container,on){container.dataset.layoutEditing=String(!!on);const guide=ensureGuide(container);if(guide)guide.hidden=!on;container.querySelectorAll('[data-layout-item]').forEach(el=>{el.classList.toggle('layout-editable',!!on);const h=el.querySelector('.drag-handle'),r=el.querySelector('.resize-handle');if(h){h.tabIndex=on?0:-1;h.setAttribute('aria-hidden',String(!on));}if(r){r.tabIndex=on?0:-1;r.setAttribute('aria-hidden',String(!on));}});clearGuide(container);}
function snapshot(container){const out={};container.querySelectorAll('[data-layout-item]').forEach(el=>out[el.dataset.layoutItem]=pos(el));return out;}
function metrics(container){const rect=container.getBoundingClientRect(),cs=getComputedStyle(container),gx=parseFloat(cs.columnGap)||8,gy=parseFloat(cs.rowGap)||8;return {rect,gx,gy,colW:(rect.width-gx*(COLS-1))/COLS,rowH:(rect.height-gy*(ROWS-1))/ROWS};}
function pointerCell(container,e,size,mode='move',origin=null){const m=metrics(container),x=Math.max(0,e.clientX-m.rect.left),y=Math.max(0,e.clientY-m.rect.top),col=Math.max(1,Math.min(COLS,Math.floor(x/(m.colW+m.gx))+1)),row=Math.max(1,Math.min(ROWS,Math.floor(y/(m.rowH+m.gy))+1));if(mode==='resize'&&origin){return {...origin,w:Math.max(1,Math.min(COLS-origin.col+1,col-origin.col+1)),h:Math.max(1,Math.min(ROWS-origin.row+1,row-origin.row+1))};}return {...size,col:Math.max(1,Math.min(COLS-size.w+1,col)),row:Math.max(1,Math.min(ROWS-size.h+1,row))};}
function setSelection(container,item){container.querySelectorAll('[data-layout-item].selected').forEach(x=>x.classList.remove('selected'));if(item)item.classList.add('selected');return item?item.dataset.layoutItem:null;}
function place(container,id,p){const item=container.querySelector(`[data-layout-item="${id}"]`);if(!item)return false;p={...pos(item),...p};p.col=Math.max(1,Math.min(COLS-p.w+1,p.col));p.row=Math.max(1,Math.min(ROWS-p.h+1,p.row));if(!canPlace(container,item,p))return false;setPos(item,p,true);paintGuide(container,p,true);return true;}
function center(container,id,axis='both'){const item=container.querySelector(`[data-layout-item="${id}"]`);if(!item)return false;const p=pos(item),q={...p};if(axis==='both'||axis==='x')q.col=Math.floor((COLS-q.w)/2)+1;if(axis==='both'||axis==='y')q.row=Math.floor((ROWS-q.h)/2)+1;return place(container,id,q);}
function bindGrid(container,{onGrid,onCollision,onSelect}={}){let drag=null;
 function select(item){const id=setSelection(container,item);if(onSelect)onSelect(id,item?pos(item):null);}
 container.addEventListener('pointerdown',e=>{if(container.dataset.layoutEditing!=='true')return;const control=e.target.closest&&e.target.closest('.drag-handle,.resize-handle');const item=control&&control.closest('[data-layout-item]');if(!item||item.hidden)return;e.preventDefault();select(item);const origin=pos(item),mode=control.classList.contains('resize-handle')?'resize':'move';drag={item,origin,last:origin,control,pointerId:e.pointerId,mode};item.classList.add('dragging');try{control.setPointerCapture(e.pointerId);}catch{}paintGuide(container,origin,true);});
 container.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.pointerId)return;e.preventDefault();const candidate=pointerCell(container,e,drag.origin,drag.mode,drag.origin),valid=canPlace(container,drag.item,candidate);paintGuide(container,candidate,valid);drag.item.classList.toggle('collision',!valid);if(valid){drag.last=candidate;setPos(drag.item,candidate,false);if(onSelect)onSelect(drag.item.dataset.layoutItem,candidate);}});
 function finish(e,cancel=false){if(!drag)return;if(e&&e.pointerId!==undefined&&e.pointerId!==drag.pointerId)return;const d=drag;drag=null;d.item.classList.remove('dragging','collision');const final=cancel?d.origin:d.last;setPos(d.item,final,true);clearGuide(container);if(!cancel&&JSON.stringify(final)!==JSON.stringify(d.origin)&&onGrid)onGrid(snapshot(container),d.item.dataset.layoutItem);}
 container.addEventListener('pointerup',e=>finish(e,false));container.addEventListener('pointercancel',e=>finish(e,true));
 container.addEventListener('click',e=>{if(container.dataset.layoutEditing!=='true')return;const item=e.target.closest&&e.target.closest('[data-layout-item]');if(item)select(item);});
 container.addEventListener('keydown',e=>{if(container.dataset.layoutEditing!=='true')return;const control=e.target.closest&&e.target.closest('.drag-handle,.resize-handle'),item=control&&control.closest('[data-layout-item]');if(!item)return;select(item);const p=pos(item),next={...p};let handled=true;if(control.classList.contains('resize-handle')){if(e.key==='ArrowLeft')next.w--;else if(e.key==='ArrowRight')next.w++;else if(e.key==='ArrowUp')next.h--;else if(e.key==='ArrowDown')next.h++;else handled=false;}else{if(e.key==='ArrowLeft')next.col--;else if(e.key==='ArrowRight')next.col++;else if(e.key==='ArrowUp')next.row--;else if(e.key==='ArrowDown')next.row++;else handled=false;}if(!handled)return;e.preventDefault();if(canPlace(container,item,next)){setPos(item,next,true);paintGuide(container,next,true);if(onGrid)onGrid(snapshot(container),item.dataset.layoutItem);if(onSelect)onSelect(item.dataset.layoutItem,next);}else{paintGuide(container,next,false);item.classList.add('collision');setTimeout(()=>item.classList.remove('collision'),160);if(onCollision)onCollision(item.dataset.layoutItem);}});
}
root.BlobbyLayout={COLS,ROWS,apply,usePreset,enableEditor,bindGrid,snapshot,canPlace,place,center,pos,setPos};
})(window);
